"""Shared dashboard control values."""

GREEDY_SCHEDULER = "Greedy value density"
EXACT_MIP_SCHEDULER = "Exact MIP snapshot"
PLANNED_SCHEDULERS = (
    "Hybrid bounded-time scheduler",
    "Local search repair",
    "Adaptive large neighborhood search",
    "Column generation",
    "Robust optimization",
    "Stochastic model with recourse",
)

AVAILABLE_SCHEDULERS = (
    GREEDY_SCHEDULER,
    EXACT_MIP_SCHEDULER,
)

SMALL_EXPERIMENT = "Small"
LARGE_EXPERIMENT = "Large"

EXPERIMENT_SIZES = (
    SMALL_EXPERIMENT,
    LARGE_EXPERIMENT,
)
SNAPSHOT_LAST_RESULT_KEY = "snapshot_last_result"
SNAPSHOT_RUN_STATUS_KEY = "snapshot_run_status"
SNAPSHOT_LAST_ERROR_KEY = "snapshot_last_error"
SNAPSHOT_RUN_HISTORY_KEY = "snapshot_run_history"

SIMULATION_LAST_RESULT_KEY = "simulation_last_result"
SIMULATION_RUN_STATUS_KEY = "simulation_run_status"
SIMULATION_LAST_ERROR_KEY = "simulation_last_error"
SIMULATION_RUN_HISTORY_KEY = "simulation_run_history"


NODE_MIN = 1
NODE_MAX = 100
NODE_DEFAULT = 8

TOTAL_GPUS_PER_NODE_DEFAULT = 8
GPU_DEMAND_MIN_VALUE = 1
GPU_DEMAND_MAX_VALUE = 64
GPU_DEMAND_MIN_DEFAULT = 1
GPU_DEMAND_MAX_DEFAULT = 16

NODE_AVAILABLE_GPU_MIN = 0
NODE_AVAILABLE_GPU_MAX = TOTAL_GPUS_PER_NODE_DEFAULT

JOB_MIN = 1
LARGE_JOB_MAX = 500
LARGE_JOB_DEFAULT = 100
PUBLIC_EXACT_SNAPSHOT_JOB_MAX = 500

SEED_MIN = 0
SEED_MAX = 100_000
SNAPSHOT_SEED_DEFAULT = 27
SIMULATION_SEED_DEFAULT = 42

DEADLINE_WEIGHT_MIN = 0.0
DEADLINE_WEIGHT_MAX = 10.0
SNAPSHOT_DEADLINE_WEIGHT_DEFAULT = 1.0
SIMULATION_DEADLINE_WEIGHT_DEFAULT = 1.0

MIP_TIME_LIMIT_MIN = 1
MIP_TIME_LIMIT_MAX = 60
SNAPSHOT_MIP_TIME_LIMIT_DEFAULT = 10
SIMULATION_MIP_TIME_LIMIT_DEFAULT = 10

PUBLIC_EXACT_SNAPSHOT_TIME_LIMIT_MAX = 60
PUBLIC_EXACT_SIMULATION_TIME_LIMIT_MAX = 60

MIP_GAP_MIN = 0.00
MIP_GAP_MAX = 0.50
SNAPSHOT_MIP_GAP_DEFAULT = 0.05
SIMULATION_MIP_GAP_DEFAULT = 0.10

SIMULATION_HORIZON_MIN = 1
SIMULATION_HORIZON_MAX = 50
SIMULATION_HORIZON_DEFAULT = 25
SIMULATION_EXACT_HORIZON_DEFAULT = 25
PUBLIC_EXACT_SIMULATION_HORIZON_MAX = 50

ARRIVAL_RATE_MIN = 0.0
ARRIVAL_RATE_MAX = 20.0
ARRIVAL_RATE_DEFAULT = 3.0
ARRIVAL_RATE_STEP = 1.0

PUBLIC_SIMULATION_EXPECTED_ARRIVALS_MAX = 1_000
PUBLIC_EXACT_SIMULATION_EXPECTED_ARRIVALS_MAX = 1000

DEFAULT_AVAILABLE_CAPACITY_RATIO = 0.70